### PR TITLE
Move source code to src/

### PR DESCRIPTION
**Pull request by szepeviktor**
## Checklist:
- [x] I've read the [Contributing page](https://github.com/junaidbhura/composer-wp-pro-plugins/blob/master/CONTRIBUTING.md).
- [x] I've created an issue and referenced it here.
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

## Description

Move source code to src/ directory. As in other PHP packages.

I hope you will like it. Now [the root](https://github.com/szepeviktor/junaidbhura_composer-wp-pro-plugins/tree/move-src) contains only documents and configuration files. So nice.

Source: https://github.com/szepeviktor/github-repository-inspection/blob/master/README.md#naming-files-in-the-root-directory

### CODE REVIEW

**Review by mcaskill — APPROVED** [review]

**Comment by junaidbhura** [comment]
Thanks @szepeviktor !

I can see that the WPML file was renamed. Can you confirm that this fixes https://github.com/junaidbhura/composer-wp-pro-plugins/issues/54?

**Comment by szepeviktor** [comment]
Yes!

**Comment by szepeviktor** [comment]
You can prevent this in CI
https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/Continuous-integration-Continuous-delivery.yml#L146-L148

**Review by junaidbhura — APPROVED** [review]

**Comment by junaidbhura** [comment]
Thanks @szepeviktor a new version has been released `1.8.0`

**Comment by szepeviktor** [comment]
It was my pleasure.

**Pull request merged**
