### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by szepeviktor**
- make it like a real composer pkg
- [normalize composer.json](https://github.com/localheinz/composer-normalize)
- make a condition more testable by @phpstan

@junaidbhura What do you think?

### CODE REVIEW

**Comment by junaidbhura** [comment]
Hi @szepeviktor Thanks for the pull request!

Could you please elaborate what you mean by "make it like a real composer pkg"?

**Comment by szepeviktor** [comment]
> Could you please elaborate what you mean by "make it like a real composer pkg"?

1. Please pick any well-known Composer package
1. Look at where its namespace root is
1. You find that it is in `src/`

That is why.

**Comment by szepeviktor** [comment]
src/ separates your source files from other files!

**Comment by junaidbhura** [comment]
Understood @szepeviktor . Let me take a look at this pull request at length, and merge it if it all looks okay.

Thanks again!

**Comment by junaidbhura** [comment]
@szepeviktor Unfortunately, as I'd mentioned on the other issue, I'm going to be doing a bit of a re-write of this plugin, which will conflict with the changes you've added.

As such, I'm going to have to close this pull request, sorry about that!

Thanks again for your contribution.

**Pull request closed without merging**
