### PR TITLE
bump to dotenv 4.1.1

### PR DESCRIPTION
**Pull request by davidwebca**

### CODE REVIEW

**Comment by junaidbhura** [comment]
Hi @david-treblig could you provide some background to this? What does this solve?

**Comment by davidwebca** [comment]
Hey! Sorry, I had to make this in a rush and decided to make the pull request on a whim. It basically allows compatibility with Root's [Bedrock](https://github.com/roots/bedrock/blob/master/composer.json) since they bumped their own dotenv requirement. There's been a few changes in the initialisation of the dotenv class too, but nothing major. Sorry about the pings and annoyance since I had to rush-fork this for a project 🙏

**Comment by thuongqbd** [comment]
Hi @junaidbhura , this pull looks fine, please accept it.

**Comment by junaidbhura** [comment]
Thanks @david-treblig and @thuongqbd merging it now!

**Pull request merged**
