### PR TITLE
Updated to latest DotEnv and also add support for Polylang Woocommerce

### PR DESCRIPTION
**Pull request by danielglans**

### CODE REVIEW

**Comment by mcaskill** [comment]
👍

Thanks for this but:

1. The update to DotEnv and the added support for PLL/WC should be two separate pull requests
2. The package vendor should not change in the `composer.json`

**Comment by danielglans** [comment]
Oh sorry, i haven't quite got the hang of how to do this the right way.. Do you want me to remove this and add a new pull request?

**Comment by mcaskill** [comment]
I'm sorry for not providing more details. Since this is a pull request from your fork's `master` branch, I would recommend:

1. Create a new branch for the DotEnv update from `junaidbhura:master` then make a pull request for it.
2. Create a new branch for the Polylang Woocommerce support from `junaidbhura:master` then make a pull request for it.
3. Close this pull request with a comment mentioning the new ones.

This way you can preserver your `bechwebbkonsult:master` branch which you are probably using right now.

**Comment by danielglans** [comment]
Okey, great! Thank you so much for the information @mcaskill

**Comment by mcaskill** [comment]
Cheers!

**Comment by junaidbhura** [comment]
Haha appreciate this. Closing this PR in anticipation of your other PRs, as discussed in the comments. Please do not update the `composer.json` file.

**Comment by mcaskill** [comment]
Well, yes, update the `composer.json`, but only to require the `^3.0`.

**Pull request closed without merging**
